import type { Locale } from './i18n/types'
import type { LocalizedName } from './countryNames'

/** ISO 3166-1 numeric → localized capital names */
export const CAPITALS: Record<string, LocalizedName> = {
  '004': { de: 'Kabul', en: 'Kabul', fr: 'Kabul' },
  '008': { de: 'Tirana', en: 'Tirana', fr: 'Tirana' },
  '012': { de: 'Algier', en: 'Algiers', fr: 'Alger' },
  '024': { de: 'Luanda', en: 'Luanda', fr: 'Luanda' },
  '031': { de: 'Baku', en: 'Baku', fr: 'Baku' },
  '032': { de: 'Buenos Aires', en: 'Buenos Aires', fr: 'Buenos Aires' },
  '036': { de: 'Canberra', en: 'Canberra', fr: 'Canberra' },
  '040': { de: 'Wien', en: 'Vienna', fr: 'Vienne' },
  '050': { de: 'Dhaka', en: 'Dhaka', fr: 'Dhaka' },
  '051': { de: 'Jerewan', en: 'Yerevan', fr: 'Erevan' },
  '056': { de: 'Brüssel', en: 'Brussels', fr: 'Bruxelles' },
  '064': { de: 'Thimphu', en: 'Thimphu', fr: 'Thimphu' },
  '068': { de: 'Sucre', en: 'Sucre', fr: 'Sucre' },
  '070': { de: 'Sarajevo', en: 'Sarajevo', fr: 'Sarajevo' },
  '072': { de: 'Gaborone', en: 'Gaborone', fr: 'Gaborone' },
  '076': { de: 'Brasília', en: 'Brasília', fr: 'Brasília' },
  '084': { de: 'Belmopan', en: 'Belmopan', fr: 'Belmopan' },
  '090': { de: 'Honiara', en: 'Honiara', fr: 'Honiara' },
  '096': { de: 'Bandar Seri Begawan', en: 'Bandar Seri Begawan', fr: 'Bandar Seri Begawan' },
  '100': { de: 'Sofia', en: 'Sofia', fr: 'Sofia' },
  '104': { de: 'Naypyidaw', en: 'Naypyidaw', fr: 'Naypyidaw' },
  '108': { de: 'Gitega', en: 'Gitega', fr: 'Gitega' },
  '112': { de: 'Minsk', en: 'Minsk', fr: 'Minsk' },
  '116': { de: 'Phnom Penh', en: 'Phnom Penh', fr: 'Phnom Penh' },
  '120': { de: 'Yaoundé', en: 'Yaoundé', fr: 'Yaoundé' },
  '124': { de: 'Ottawa', en: 'Ottawa', fr: 'Ottawa' },
  '140': { de: 'Bangui', en: 'Bangui', fr: 'Bangui' },
  '144': { de: 'Sri Jayawardenepura Kotte', en: 'Sri Jayawardenepura Kotte', fr: 'Sri Jayawardenepura Kotte' },
  '152': { de: 'Santiago', en: 'Santiago', fr: 'Santiago' },
  '156': { de: 'Peking', en: 'Beijing', fr: 'Pékin' },
  '158': { de: 'Taipeh', en: 'Taipei', fr: 'Taipei' },
  '170': { de: 'Bogotá', en: 'Bogotá', fr: 'Bogotá' },
  '178': { de: 'Brazzaville', en: 'Brazzaville', fr: 'Brazzaville' },
  '180': { de: 'Kinshasa', en: 'Kinshasa', fr: 'Kinshasa' },
  '188': { de: 'San José', en: 'San José', fr: 'San José' },
  '191': { de: 'Zagreb', en: 'Zagreb', fr: 'Zagreb' },
  '192': { de: 'Havanna', en: 'Havana', fr: 'La Havane' },
  '196': { de: 'Nikosia', en: 'Nicosia', fr: 'Nicosie' },
  '203': { de: 'Prag', en: 'Prague', fr: 'Prague' },
  '204': { de: 'Porto-Novo', en: 'Porto-Novo', fr: 'Porto-Novo' },
  '208': { de: 'Kopenhagen', en: 'Copenhagen', fr: 'Copenhague' },
  '214': { de: 'Santo Domingo', en: 'Santo Domingo', fr: 'Santo Domingo' },
  '218': { de: 'Quito', en: 'Quito', fr: 'Quito' },
  '222': { de: 'San Salvador', en: 'San Salvador', fr: 'San Salvador' },
  '226': { de: 'Malabo', en: 'Malabo', fr: 'Malabo' },
  '231': { de: 'Addis Abeba', en: 'Addis Abeba', fr: 'Addis Abeba' },
  '232': { de: 'Asmara', en: 'Asmara', fr: 'Asmara' },
  '233': { de: 'Tallinn', en: 'Tallinn', fr: 'Tallinn' },
  '242': { de: 'Suva', en: 'Suva', fr: 'Suva' },
  '246': { de: 'Helsinki', en: 'Helsinki', fr: 'Helsinki' },
  '250': { de: 'Paris', en: 'Paris', fr: 'Paris' },
  '262': { de: 'Dschibuti', en: 'Djibouti', fr: 'Djibouti' },
  '266': { de: 'Libreville', en: 'Libreville', fr: 'Libreville' },
  '268': { de: 'Tiflis', en: 'Tbilisi', fr: 'Tbilissi' },
  '270': { de: 'Banjul', en: 'Banjul', fr: 'Banjul' },
  '276': { de: 'Berlin', en: 'Berlin', fr: 'Berlin' },
  '288': { de: 'Accra', en: 'Accra', fr: 'Accra' },
  '300': { de: 'Athen', en: 'Athens', fr: 'Athènes' },
  '320': { de: 'Guatemala-Stadt', en: 'Guatemala City', fr: 'Guatemala' },
  '324': { de: 'Conakry', en: 'Conakry', fr: 'Conakry' },
  '328': { de: 'Georgetown', en: 'Georgetown', fr: 'Georgetown' },
  '332': { de: 'Port-au-Prince', en: 'Port-au-Prince', fr: 'Port-au-Prince' },
  '340': { de: 'Tegucigalpa', en: 'Tegucigalpa', fr: 'Tegucigalpa' },
  '348': { de: 'Budapest', en: 'Budapest', fr: 'Budapest' },
  '352': { de: 'Reykjavík', en: 'Reykjavík', fr: 'Reykjavík' },
  '356': { de: 'Neu-Delhi', en: 'New Delhi', fr: 'New Delhi' },
  '360': { de: 'Jakarta', en: 'Jakarta', fr: 'Jakarta' },
  '364': { de: 'Teheran', en: 'Tehran', fr: 'Téhéran' },
  '368': { de: 'Bagdad', en: 'Bagdad', fr: 'Bagdad' },
  '372': { de: 'Dublin', en: 'Dublin', fr: 'Dublin' },
  '376': { de: 'Jerusalem', en: 'Jerusalem', fr: 'Jerusalem' },
  '380': { de: 'Rom', en: 'Rome', fr: 'Rome' },
  '384': { de: 'Yamoussoukro', en: 'Yamoussoukro', fr: 'Yamoussoukro' },
  '388': { de: 'Kingston', en: 'Kingston', fr: 'Kingston' },
  '392': { de: 'Tokio', en: 'Tokyo', fr: 'Tokyo' },
  '398': { de: 'Astana', en: 'Astana', fr: 'Astana' },
  '400': { de: 'Amman', en: 'Amman', fr: 'Amman' },
  '404': { de: 'Nairobi', en: 'Nairobi', fr: 'Nairobi' },
  '408': { de: 'Pjöngjang', en: 'Pyongyang', fr: 'Pyongyang' },
  '410': { de: 'Seoul', en: 'Seoul', fr: 'Seoul' },
  '414': { de: 'Kuwait-Stadt', en: 'Kuwait City', fr: 'Koweït' },
  '417': { de: 'Bischkek', en: 'Bishkek', fr: 'Bichkek' },
  '418': { de: 'Vientiane', en: 'Vientiane', fr: 'Vientiane' },
  '422': { de: 'Beirut', en: 'Beirut', fr: 'Beirut' },
  '426': { de: 'Maseru', en: 'Maseru', fr: 'Maseru' },
  '428': { de: 'Riga', en: 'Riga', fr: 'Riga' },
  '430': { de: 'Monrovia', en: 'Monrovia', fr: 'Monrovia' },
  '434': { de: 'Tripolis', en: 'Tripoli', fr: 'Tripoli' },
  '440': { de: 'Vilnius', en: 'Vilnius', fr: 'Vilnius' },
  '442': { de: 'Luxemburg', en: 'Luxemburg', fr: 'Luxemburg' },
  '450': { de: 'Antananarivo', en: 'Antananarivo', fr: 'Antananarivo' },
  '454': { de: 'Lilongwe', en: 'Lilongwe', fr: 'Lilongwe' },
  '458': { de: 'Kuala Lumpur', en: 'Kuala Lumpur', fr: 'Kuala Lumpur' },
  '466': { de: 'Bamako', en: 'Bamako', fr: 'Bamako' },
  '478': { de: 'Nouakchott', en: 'Nouakchott', fr: 'Nouakchott' },
  '484': { de: 'Mexiko-Stadt', en: 'Mexico City', fr: 'Mexico' },
  '496': { de: 'Ulaanbaatar', en: 'Ulaanbaatar', fr: 'Ulaanbaatar' },
  '498': { de: 'Chișinău', en: 'Chișinău', fr: 'Chișinău' },
  '499': { de: 'Podgorica', en: 'Podgorica', fr: 'Podgorica' },
  '504': { de: 'Rabat', en: 'Rabat', fr: 'Rabat' },
  '508': { de: 'Maputo', en: 'Maputo', fr: 'Maputo' },
  '512': { de: 'Maskat', en: 'Muscat', fr: 'Mascate' },
  '516': { de: 'Windhoek', en: 'Windhoek', fr: 'Windhoek' },
  '524': { de: 'Kathmandu', en: 'Kathmandu', fr: 'Kathmandu' },
  '528': { de: 'Amsterdam', en: 'Amsterdam', fr: 'Amsterdam' },
  '548': { de: 'Port Vila', en: 'Port Vila', fr: 'Port Vila' },
  '554': { de: 'Wellington', en: 'Wellington', fr: 'Wellington' },
  '558': { de: 'Managua', en: 'Managua', fr: 'Managua' },
  '562': { de: 'Niamey', en: 'Niamey', fr: 'Niamey' },
  '566': { de: 'Abuja', en: 'Abuja', fr: 'Abuja' },
  '578': { de: 'Oslo', en: 'Oslo', fr: 'Oslo' },
  '586': { de: 'Islamabad', en: 'Islamabad', fr: 'Islamabad' },
  '591': { de: 'Panama-Stadt', en: 'Panama City', fr: 'Panama' },
  '598': { de: 'Port Moresby', en: 'Port Moresby', fr: 'Port Moresby' },
  '600': { de: 'Asunción', en: 'Asunción', fr: 'Asunción' },
  '604': { de: 'Lima', en: 'Lima', fr: 'Lima' },
  '608': { de: 'Manila', en: 'Manila', fr: 'Manila' },
  '616': { de: 'Warschau', en: 'Warsaw', fr: 'Varsovie' },
  '620': { de: 'Lissabon', en: 'Lisbon', fr: 'Lisbonne' },
  '624': { de: 'Bissau', en: 'Bissau', fr: 'Bissau' },
  '626': { de: 'Dili', en: 'Dili', fr: 'Dili' },
  '634': { de: 'Doha', en: 'Doha', fr: 'Doha' },
  '642': { de: 'Bukarest', en: 'Bucharest', fr: 'Bucarest' },
  '643': { de: 'Moskau', en: 'Moscow', fr: 'Moscou' },
  '646': { de: 'Kigali', en: 'Kigali', fr: 'Kigali' },
  '682': { de: 'Riad', en: 'Riyadh', fr: 'Riyad' },
  '686': { de: 'Dakar', en: 'Dakar', fr: 'Dakar' },
  '688': { de: 'Belgrad', en: 'Belgrad', fr: 'Belgrad' },
  '694': { de: 'Freetown', en: 'Freetown', fr: 'Freetown' },
  '703': { de: 'Bratislava', en: 'Bratislava', fr: 'Bratislava' },
  '704': { de: 'Hanoi', en: 'Hanoi', fr: 'Hanoi' },
  '705': { de: 'Ljubljana', en: 'Ljubljana', fr: 'Ljubljana' },
  '706': { de: 'Mogadischu', en: 'Mogadishu', fr: 'Mogadiscio' },
  '710': { de: 'Pretoria', en: 'Pretoria', fr: 'Pretoria' },
  '716': { de: 'Harare', en: 'Harare', fr: 'Harare' },
  '724': { de: 'Madrid', en: 'Madrid', fr: 'Madrid' },
  '728': { de: 'Juba', en: 'Juba', fr: 'Juba' },
  '729': { de: 'Khartum', en: 'Khartoum', fr: 'Khartoum' },
  '740': { de: 'Paramaribo', en: 'Paramaribo', fr: 'Paramaribo' },
  '748': { de: 'Mbabane', en: 'Mbabane', fr: 'Mbabane' },
  '752': { de: 'Stockholm', en: 'Stockholm', fr: 'Stockholm' },
  '756': { de: 'Bern', en: 'Bern', fr: 'Bern' },
  '760': { de: 'Damaskus', en: 'Damascus', fr: 'Damas' },
  '762': { de: 'Duschanbe', en: 'Dushanbe', fr: 'Douchanbé' },
  '764': { de: 'Bangkok', en: 'Bangkok', fr: 'Bangkok' },
  '768': { de: 'Lomé', en: 'Lomé', fr: 'Lomé' },
  '780': { de: 'Port of Spain', en: 'Port of Spain', fr: 'Port of Spain' },
  '784': { de: 'Abu Dhabi', en: 'Abu Dhabi', fr: 'Abu Dhabi' },
  '788': { de: 'Tunis', en: 'Tunis', fr: 'Tunis' },
  '792': { de: 'Ankara', en: 'Ankara', fr: 'Ankara' },
  '795': { de: 'Aschgabat', en: 'Ashgabat', fr: 'Achgabat' },
  '800': { de: 'Kampala', en: 'Kampala', fr: 'Kampala' },
  '804': { de: 'Kiew', en: 'Kyiv', fr: 'Kiev' },
  '807': { de: 'Skopje', en: 'Skopje', fr: 'Skopje' },
  '818': { de: 'Kairo', en: 'Cairo', fr: 'Le Caire' },
  '826': { de: 'London', en: 'London', fr: 'Londres' },
  '834': { de: 'Dodoma', en: 'Dodoma', fr: 'Dodoma' },
  '840': { de: 'Washington, D.C.', en: 'Washington, D.C.', fr: 'Washington' },
  '854': { de: 'Ouagadougou', en: 'Ouagadougou', fr: 'Ouagadougou' },
  '858': { de: 'Montevideo', en: 'Montevideo', fr: 'Montevideo' },
  '860': { de: 'Taschkent', en: 'Tashkent', fr: 'Tachkent' },
  '862': { de: 'Caracas', en: 'Caracas', fr: 'Caracas' },
  '887': { de: 'Sanaa', en: 'Sanaa', fr: 'Sanaa' },
  '894': { de: 'Lusaka', en: 'Lusaka', fr: 'Lusaka' },
}

export function capitalOf(countryId: string, locale: Locale = 'de'): string | null {
  const entry = CAPITALS[countryId]
  if (!entry) return null
  return entry[locale] ?? entry.de
}

export function hasCapital(countryId: string): boolean {
  return countryId in CAPITALS
}
