import type { Locale } from './i18n/types'

export type LocalizedName = { de: string; en: string; fr: string }

/** ISO 3166-1 numeric → localized country names */
export const COUNTRY_NAMES: Record<string, LocalizedName> = {
  '004': { de: 'Afghanistan', en: 'Afghanistan', fr: 'Afghanistan' },
  '008': { de: 'Albanien', en: 'Albania', fr: 'Albanie' },
  '010': { de: 'Antarktis', en: 'Antarctica', fr: 'Antarctique' },
  '012': { de: 'Algerien', en: 'Algeria', fr: 'Algérie' },
  '020': { de: 'Andorra', en: 'Andorra', fr: 'Andorre' },
  '024': { de: 'Angola', en: 'Angola', fr: 'Angola' },
  '028': { de: 'Antigua und Barbuda', en: 'Antigua and Barbuda', fr: 'Antigua-et-Barbuda' },
  '031': { de: 'Aserbaidschan', en: 'Azerbaijan', fr: 'Azerbaïdjan' },
  '032': { de: 'Argentinien', en: 'Argentina', fr: 'Argentine' },
  '036': { de: 'Australien', en: 'Australia', fr: 'Australie' },
  '040': { de: 'Österreich', en: 'Austria', fr: 'Autriche' },
  '044': { de: 'Bahamas', en: 'Bahamas', fr: 'Bahamas' },
  '048': { de: 'Bahrain', en: 'Bahrain', fr: 'Bahreïn' },
  '050': { de: 'Bangladesch', en: 'Bangladesh', fr: 'Bangladesh' },
  '051': { de: 'Armenien', en: 'Armenia', fr: 'Arménie' },
  '052': { de: 'Barbados', en: 'Barbados', fr: 'Barbade' },
  '056': { de: 'Belgien', en: 'Belgium', fr: 'Belgique' },
  '064': { de: 'Bhutan', en: 'Bhutan', fr: 'Bhoutan' },
  '068': { de: 'Bolivien', en: 'Bolivia', fr: 'Bolivie' },
  '070': { de: 'Bosnien und Herzegowina', en: 'Bosnia and Herzegovina', fr: 'Bosnie-Herzégovine' },
  '072': { de: 'Botswana', en: 'Botswana', fr: 'Botswana' },
  '076': { de: 'Brasilien', en: 'Brazil', fr: 'Brésil' },
  '084': { de: 'Belize', en: 'Belize', fr: 'Belize' },
  '090': { de: 'Salomonen', en: 'Solomon Islands', fr: 'Salomon' },
  '096': { de: 'Brunei', en: 'Brunei', fr: 'Brunei' },
  '100': { de: 'Bulgarien', en: 'Bulgaria', fr: 'Bulgarie' },
  '104': { de: 'Myanmar', en: 'Myanmar', fr: 'Myanmar' },
  '108': { de: 'Burundi', en: 'Burundi', fr: 'Burundi' },
  '112': { de: 'Belarus', en: 'Belarus', fr: 'Biélorussie' },
  '116': { de: 'Kambodscha', en: 'Cambodia', fr: 'Cambodge' },
  '120': { de: 'Kamerun', en: 'Cameroon', fr: 'Cameroun' },
  '124': { de: 'Kanada', en: 'Canada', fr: 'Canada' },
  '140': { de: 'Zentralafrikanische Republik', en: 'Central African Republic', fr: 'République centrafricaine' },
  '144': { de: 'Sri Lanka', en: 'Sri Lanka', fr: 'Sri Lanka' },
  '148': { de: 'Tschad', en: 'Chad', fr: 'Tchad' },
  '152': { de: 'Chile', en: 'Chile', fr: 'Chili' },
  '156': { de: 'China', en: 'China', fr: 'Chine' },
  '158': { de: 'Taiwan', en: 'Taiwan', fr: 'Taïwan' },
  '170': { de: 'Kolumbien', en: 'Colombia', fr: 'Colombie' },
  '174': { de: 'Komoren', en: 'Comoros', fr: 'Comores' },
  '178': { de: 'Republik Kongo', en: 'Republic of the Congo', fr: 'République du Congo' },
  '180': { de: 'Demokratische Republik Kongo', en: 'Democratic Republic of the Congo', fr: 'République démocratique du Congo' },
  '188': { de: 'Costa Rica', en: 'Costa Rica', fr: 'Costa Rica' },
  '191': { de: 'Kroatien', en: 'Croatia', fr: 'Croatie' },
  '192': { de: 'Kuba', en: 'Cuba', fr: 'Cuba' },
  '196': { de: 'Zypern', en: 'Cyprus', fr: 'Chypre' },
  '203': { de: 'Tschechien', en: 'Czechia', fr: 'Tchéquie' },
  '204': { de: 'Benin', en: 'Benin', fr: 'Bénin' },
  '208': { de: 'Dänemark', en: 'Denmark', fr: 'Danemark' },
  '212': { de: 'Dominica', en: 'Dominica', fr: 'Dominique' },
  '214': { de: 'Dominikanische Republik', en: 'Dominican Republic', fr: 'République dominicaine' },
  '218': { de: 'Ecuador', en: 'Ecuador', fr: 'Équateur' },
  '222': { de: 'El Salvador', en: 'El Salvador', fr: 'Salvador' },
  '226': { de: 'Äquatorialguinea', en: 'Equatorial Guinea', fr: 'Guinée équatoriale' },
  '231': { de: 'Äthiopien', en: 'Ethiopia', fr: 'Éthiopie' },
  '232': { de: 'Eritrea', en: 'Eritrea', fr: 'Érythrée' },
  '233': { de: 'Estland', en: 'Estonia', fr: 'Estonie' },
  '238': { de: 'Falklandinseln', en: 'Falkland Islands', fr: 'Îles Malouines' },
  '242': { de: 'Fidschi', en: 'Fiji', fr: 'Fidji' },
  '246': { de: 'Finnland', en: 'Finland', fr: 'Finlande' },
  '250': { de: 'Frankreich', en: 'France', fr: 'France' },
  '260': { de: 'Französische Süd- und Antarktisgebiete', en: 'French Southern Territories', fr: 'Terres australes françaises' },
  '262': { de: 'Dschibuti', en: 'Djibouti', fr: 'Djibouti' },
  '266': { de: 'Gabun', en: 'Gabon', fr: 'Gabon' },
  '268': { de: 'Georgien', en: 'Georgia', fr: 'Géorgie' },
  '270': { de: 'Gambia', en: 'Gambia', fr: 'Gambie' },
  '275': { de: 'Palästina', en: 'Palestine', fr: 'Palestine' },
  '276': { de: 'Deutschland', en: 'Germany', fr: 'Allemagne' },
  '288': { de: 'Ghana', en: 'Ghana', fr: 'Ghana' },
  '300': { de: 'Griechenland', en: 'Greece', fr: 'Grèce' },
  '304': { de: 'Grönland', en: 'Greenland', fr: 'Groenland' },
  '320': { de: 'Guatemala', en: 'Guatemala', fr: 'Guatemala' },
  '324': { de: 'Guinea', en: 'Guinea', fr: 'Guinée' },
  '328': { de: 'Guyana', en: 'Guyana', fr: 'Guyana' },
  '332': { de: 'Haiti', en: 'Haiti', fr: 'Haïti' },
  '340': { de: 'Honduras', en: 'Honduras', fr: 'Honduras' },
  '348': { de: 'Ungarn', en: 'Hungary', fr: 'Hongrie' },
  '352': { de: 'Island', en: 'Iceland', fr: 'Islande' },
  '356': { de: 'Indien', en: 'India', fr: 'Inde' },
  '360': { de: 'Indonesien', en: 'Indonesia', fr: 'Indonésie' },
  '364': { de: 'Iran', en: 'Iran', fr: 'Iran' },
  '368': { de: 'Irak', en: 'Iraq', fr: 'Irak' },
  '372': { de: 'Irland', en: 'Ireland', fr: 'Irlande' },
  '376': { de: 'Israel', en: 'Israel', fr: 'Israël' },
  '380': { de: 'Italien', en: 'Italy', fr: 'Italie' },
  '384': { de: 'Elfenbeinküste', en: 'Ivory Coast', fr: 'Côte d\'Ivoire' },
  '388': { de: 'Jamaika', en: 'Jamaica', fr: 'Jamaïque' },
  '392': { de: 'Japan', en: 'Japan', fr: 'Japon' },
  '398': { de: 'Kasachstan', en: 'Kazakhstan', fr: 'Kazakhstan' },
  '400': { de: 'Jordanien', en: 'Jordan', fr: 'Jordanie' },
  '404': { de: 'Kenia', en: 'Kenya', fr: 'Kenya' },
  '408': { de: 'Nordkorea', en: 'North Korea', fr: 'Corée du Nord' },
  '410': { de: 'Südkorea', en: 'South Korea', fr: 'Corée du Sud' },
  '414': { de: 'Kuwait', en: 'Kuwait', fr: 'Koweït' },
  '417': { de: 'Kirgisistan', en: 'Kyrgyzstan', fr: 'Kirghizistan' },
  '418': { de: 'Laos', en: 'Laos', fr: 'Laos' },
  '422': { de: 'Libanon', en: 'Lebanon', fr: 'Liban' },
  '426': { de: 'Lesotho', en: 'Lesotho', fr: 'Lesotho' },
  '428': { de: 'Lettland', en: 'Latvia', fr: 'Lettonie' },
  '430': { de: 'Liberia', en: 'Liberia', fr: 'Liberia' },
  '434': { de: 'Libyen', en: 'Libya', fr: 'Libye' },
  '440': { de: 'Litauen', en: 'Lithuania', fr: 'Lituanie' },
  '442': { de: 'Luxemburg', en: 'Luxembourg', fr: 'Luxembourg' },
  '450': { de: 'Madagaskar', en: 'Madagascar', fr: 'Madagascar' },
  '454': { de: 'Malawi', en: 'Malawi', fr: 'Malawi' },
  '458': { de: 'Malaysia', en: 'Malaysia', fr: 'Malaisie' },
  '462': { de: 'Malediven', en: 'Maldives', fr: 'Maldives' },
  '466': { de: 'Mali', en: 'Mali', fr: 'Mali' },
  '478': { de: 'Mauretanien', en: 'Mauritania', fr: 'Mauritanie' },
  '480': { de: 'Mauritius', en: 'Mauritius', fr: 'Maurice' },
  '484': { de: 'Mexiko', en: 'Mexico', fr: 'Mexique' },
  '496': { de: 'Mongolei', en: 'Mongolia', fr: 'Mongolie' },
  '498': { de: 'Moldau', en: 'Moldova', fr: 'Moldavie' },
  '499': { de: 'Montenegro', en: 'Montenegro', fr: 'Monténégro' },
  '504': { de: 'Marokko', en: 'Morocco', fr: 'Maroc' },
  '508': { de: 'Mosambik', en: 'Mozambique', fr: 'Mozambique' },
  '512': { de: 'Oman', en: 'Oman', fr: 'Oman' },
  '516': { de: 'Namibia', en: 'Namibia', fr: 'Namibie' },
  '524': { de: 'Nepal', en: 'Nepal', fr: 'Népal' },
  '528': { de: 'Niederlande', en: 'Netherlands', fr: 'Pays-Bas' },
  '540': { de: 'Neukaledonien', en: 'New Caledonia', fr: 'Nouvelle-Calédonie' },
  '548': { de: 'Vanuatu', en: 'Vanuatu', fr: 'Vanuatu' },
  '554': { de: 'Neuseeland', en: 'New Zealand', fr: 'Nouvelle-Zélande' },
  '558': { de: 'Nicaragua', en: 'Nicaragua', fr: 'Nicaragua' },
  '562': { de: 'Niger', en: 'Niger', fr: 'Niger' },
  '566': { de: 'Nigeria', en: 'Nigeria', fr: 'Nigeria' },
  '578': { de: 'Norwegen', en: 'Norway', fr: 'Norvège' },
  '586': { de: 'Pakistan', en: 'Pakistan', fr: 'Pakistan' },
  '591': { de: 'Panama', en: 'Panama', fr: 'Panama' },
  '598': { de: 'Papua-Neuguinea', en: 'Papua New Guinea', fr: 'Papouasie-Nouvelle-Guinée' },
  '600': { de: 'Paraguay', en: 'Paraguay', fr: 'Paraguay' },
  '604': { de: 'Peru', en: 'Peru', fr: 'Pérou' },
  '608': { de: 'Philippinen', en: 'Philippines', fr: 'Philippines' },
  '616': { de: 'Polen', en: 'Poland', fr: 'Pologne' },
  '620': { de: 'Portugal', en: 'Portugal', fr: 'Portugal' },
  '624': { de: 'Guinea-Bissau', en: 'Guinea-Bissau', fr: 'Guinée-Bissau' },
  '626': { de: 'Osttimor', en: 'East Timor', fr: 'Timor oriental' },
  '630': { de: 'Puerto Rico', en: 'Puerto Rico', fr: 'Porto Rico' },
  '634': { de: 'Katar', en: 'Qatar', fr: 'Qatar' },
  '642': { de: 'Rumänien', en: 'Romania', fr: 'Roumanie' },
  '643': { de: 'Russland', en: 'Russia', fr: 'Russie' },
  '646': { de: 'Ruanda', en: 'Rwanda', fr: 'Rwanda' },
  '682': { de: 'Saudi-Arabien', en: 'Saudi Arabia', fr: 'Arabie saoudite' },
  '686': { de: 'Senegal', en: 'Senegal', fr: 'Sénégal' },
  '688': { de: 'Serbien', en: 'Serbia', fr: 'Serbie' },
  '694': { de: 'Sierra Leone', en: 'Sierra Leone', fr: 'Sierra Leone' },
  '702': { de: 'Singapur', en: 'Singapore', fr: 'Singapour' },
  '703': { de: 'Slowakei', en: 'Slovakia', fr: 'Slovaquie' },
  '704': { de: 'Vietnam', en: 'Vietnam', fr: 'Viêt Nam' },
  '705': { de: 'Slowenien', en: 'Slovenia', fr: 'Slovénie' },
  '706': { de: 'Somalia', en: 'Somalia', fr: 'Somalie' },
  '710': { de: 'Südafrika', en: 'South Africa', fr: 'Afrique du Sud' },
  '716': { de: 'Simbabwe', en: 'Zimbabwe', fr: 'Zimbabwe' },
  '724': { de: 'Spanien', en: 'Spain', fr: 'Espagne' },
  '728': { de: 'Südsudan', en: 'South Sudan', fr: 'Soudan du Sud' },
  '729': { de: 'Sudan', en: 'Sudan', fr: 'Soudan' },
  '732': { de: 'Westsahara', en: 'Western Sahara', fr: 'Sahara occidental' },
  '740': { de: 'Suriname', en: 'Suriname', fr: 'Suriname' },
  '748': { de: 'Eswatini', en: 'eSwatini', fr: 'Eswatini' },
  '752': { de: 'Schweden', en: 'Sweden', fr: 'Suède' },
  '756': { de: 'Schweiz', en: 'Switzerland', fr: 'Suisse' },
  '760': { de: 'Syrien', en: 'Syria', fr: 'Syrie' },
  '762': { de: 'Tadschikistan', en: 'Tajikistan', fr: 'Tadjikistan' },
  '764': { de: 'Thailand', en: 'Thailand', fr: 'Thaïlande' },
  '768': { de: 'Togo', en: 'Togo', fr: 'Togo' },
  '780': { de: 'Trinidad und Tobago', en: 'Trinidad and Tobago', fr: 'Trinité-et-Tobago' },
  '784': { de: 'Vereinigte Arabische Emirate', en: 'United Arab Emirates', fr: 'Émirats arabes unis' },
  '788': { de: 'Tunesien', en: 'Tunisia', fr: 'Tunisie' },
  '792': { de: 'Türkei', en: 'Turkey', fr: 'Turquie' },
  '795': { de: 'Turkmenistan', en: 'Turkmenistan', fr: 'Turkménistan' },
  '800': { de: 'Uganda', en: 'Uganda', fr: 'Ouganda' },
  '804': { de: 'Ukraine', en: 'Ukraine', fr: 'Ukraine' },
  '807': { de: 'Nordmazedonien', en: 'Macedonia', fr: 'Macédoine du Nord' },
  '818': { de: 'Ägypten', en: 'Egypt', fr: 'Égypte' },
  '826': { de: 'Vereinigtes Königreich', en: 'United Kingdom', fr: 'Royaume-Uni' },
  '834': { de: 'Tansania', en: 'Tanzania', fr: 'Tanzanie' },
  '840': { de: 'Vereinigte Staaten', en: 'United States', fr: 'États-Unis' },
  '854': { de: 'Burkina Faso', en: 'Burkina Faso', fr: 'Burkina Faso' },
  '858': { de: 'Uruguay', en: 'Uruguay', fr: 'Uruguay' },
  '860': { de: 'Usbekistan', en: 'Uzbekistan', fr: 'Ouzbékistan' },
  '862': { de: 'Venezuela', en: 'Venezuela', fr: 'Venezuela' },
  '887': { de: 'Jemen', en: 'Yemen', fr: 'Yémen' },
  '894': { de: 'Sambia', en: 'Zambia', fr: 'Zambie' },
}

/** @deprecated use COUNTRY_NAMES */
export const COUNTRY_NAMES_DE: Record<string, string> = Object.fromEntries(
  Object.entries(COUNTRY_NAMES).map(([id, n]) => [id, n.de]),
)

/** Kleine Inselstaaten / Antarktis oft schwer klickbar — für V1 aus dem Pool nehmen */
export const EXCLUDED_IDS = new Set([
  '010', // Antarktis
  '020', // Andorra
  '028', // Antigua
  '044', // Bahamas
  '048', // Bahrain
  '052', // Barbados
  '092', // British Virgin Islands (falls vorhanden)
  '212', // Dominica
  '238', // Falkland
  '260', // Franz. Südgebiete
  '275', // Palästina (kleine Fläche)
  '304', // Grönland (optional groß, aber oft als Land verwechselt)
  '462', // Malediven
  '480', // Mauritius
  '540', // Neukaledonien
  '630', // Puerto Rico
  '702', // Singapur
  '732', // Westsahara
])

export function countryNameOf(id: string, locale: Locale = 'de'): string | null {
  const entry = COUNTRY_NAMES[id]
  if (!entry) return null
  return entry[locale] ?? entry.de
}
