import { alpha2Of } from './isoAlpha2'

/** Flaggenfarben (deutsch), grob nach sichtbaren Hauptfarben */
export type FlagColor =
  | 'rot'
  | 'blau'
  | 'grün'
  | 'gelb'
  | 'schwarz'
  | 'weiß'
  | 'orange'

export const FLAG_COLOR_OPTIONS: { id: FlagColor; label: string; hex: string }[] = [
  { id: 'rot', label: 'Rot', hex: '#c45c4a' },
  { id: 'blau', label: 'Blau', hex: '#3a7ab8' },
  { id: 'grün', label: 'Grün', hex: '#3aa87a' },
  { id: 'gelb', label: 'Gelb', hex: '#e0b84a' },
  { id: 'schwarz', label: 'Schwarz', hex: '#1a1a1a' },
  { id: 'weiß', label: 'Weiß', hex: '#eef6f4' },
  { id: 'orange', label: 'Orange', hex: '#f0a35e' },
]

/** ISO alpha-2 → Farben in der Nationalflagge */
const FLAG_COLORS_A2: Record<string, FlagColor[]> = {
  AG: ['rot', 'blau', 'gelb', 'schwarz', 'weiß'],
  BS: ['blau', 'gelb', 'schwarz'],
  BB: ['blau', 'gelb', 'schwarz'],
  KM: ['gelb', 'weiß', 'rot', 'blau', 'grün'],
  DM: ['grün', 'gelb', 'schwarz', 'weiß', 'rot'],
  PS: ['schwarz', 'weiß', 'grün', 'rot'],
  PR: ['rot', 'weiß', 'blau'],
  EH: ['schwarz', 'weiß', 'grün', 'rot'],
  GL: ['rot', 'weiß'],
  NC: ['blau', 'rot', 'grün'],
  AQ: ['weiß', 'blau'],
  FK: ['blau', 'weiß', 'rot'],
  TF: ['blau', 'weiß', 'rot'],
  AF: ['schwarz', 'rot', 'grün'],
  AL: ['rot', 'schwarz'],
  DZ: ['grün', 'weiß', 'rot'],
  AD: ['blau', 'gelb', 'rot'],
  AO: ['rot', 'schwarz', 'gelb'],
  AR: ['blau', 'weiß', 'gelb'],
  AM: ['rot', 'blau', 'orange'],
  AU: ['blau', 'rot', 'weiß'],
  AT: ['rot', 'weiß'],
  AZ: ['blau', 'rot', 'grün'],
  BH: ['rot', 'weiß'],
  BD: ['grün', 'rot'],
  BY: ['rot', 'grün', 'weiß'],
  BE: ['schwarz', 'gelb', 'rot'],
  BZ: ['blau', 'rot', 'weiß'],
  BJ: ['grün', 'gelb', 'rot'],
  BT: ['gelb', 'orange', 'weiß'],
  BO: ['rot', 'gelb', 'grün'],
  BA: ['blau', 'gelb', 'weiß'],
  BW: ['blau', 'schwarz', 'weiß'],
  BR: ['grün', 'gelb', 'blau'],
  BN: ['gelb', 'weiß', 'schwarz', 'rot'],
  BG: ['weiß', 'grün', 'rot'],
  BF: ['rot', 'grün', 'gelb'],
  BI: ['rot', 'weiß', 'grün'],
  CV: ['blau', 'weiß', 'rot', 'gelb'],
  KH: ['blau', 'rot', 'weiß'],
  CM: ['grün', 'rot', 'gelb'],
  CA: ['rot', 'weiß'],
  CF: ['blau', 'weiß', 'grün', 'gelb', 'rot'],
  TD: ['blau', 'gelb', 'rot'],
  CL: ['blau', 'weiß', 'rot'],
  CN: ['rot', 'gelb'],
  CO: ['gelb', 'blau', 'rot'],
  CG: ['grün', 'gelb', 'rot'],
  CD: ['blau', 'gelb', 'rot'],
  CR: ['blau', 'weiß', 'rot'],
  CI: ['orange', 'weiß', 'grün'],
  HR: ['rot', 'weiß', 'blau'],
  CU: ['blau', 'weiß', 'rot'],
  CY: ['weiß', 'orange'],
  CZ: ['weiß', 'rot', 'blau'],
  DK: ['rot', 'weiß'],
  DJ: ['blau', 'grün', 'weiß', 'rot'],
  DO: ['blau', 'rot', 'weiß'],
  EC: ['gelb', 'blau', 'rot'],
  EG: ['rot', 'weiß', 'schwarz'],
  SV: ['blau', 'weiß'],
  GQ: ['grün', 'weiß', 'rot', 'blau'],
  ER: ['grün', 'blau', 'rot', 'gelb'],
  EE: ['blau', 'schwarz', 'weiß'],
  SZ: ['blau', 'gelb', 'rot', 'schwarz'],
  ET: ['grün', 'gelb', 'rot'],
  FJ: ['blau', 'weiß', 'rot'],
  FI: ['weiß', 'blau'],
  FR: ['blau', 'weiß', 'rot'],
  GA: ['grün', 'gelb', 'blau'],
  GM: ['rot', 'blau', 'grün', 'weiß'],
  GE: ['weiß', 'rot'],
  DE: ['schwarz', 'rot', 'gelb'],
  GH: ['rot', 'gelb', 'grün', 'schwarz'],
  GR: ['blau', 'weiß'],
  GT: ['blau', 'weiß'],
  GN: ['rot', 'gelb', 'grün'],
  GW: ['rot', 'gelb', 'grün', 'schwarz'],
  GY: ['grün', 'gelb', 'rot', 'schwarz', 'weiß'],
  HT: ['blau', 'rot'],
  HN: ['blau', 'weiß'],
  HU: ['rot', 'weiß', 'grün'],
  IS: ['blau', 'weiß', 'rot'],
  IN: ['orange', 'weiß', 'grün'],
  ID: ['rot', 'weiß'],
  IR: ['grün', 'weiß', 'rot'],
  IQ: ['rot', 'weiß', 'schwarz', 'grün'],
  IE: ['grün', 'weiß', 'orange'],
  IL: ['weiß', 'blau'],
  IT: ['grün', 'weiß', 'rot'],
  JM: ['grün', 'gelb', 'schwarz'],
  JP: ['weiß', 'rot'],
  JO: ['schwarz', 'weiß', 'grün', 'rot'],
  KZ: ['blau', 'gelb'],
  KE: ['schwarz', 'rot', 'grün', 'weiß'],
  KW: ['grün', 'weiß', 'rot', 'schwarz'],
  KG: ['rot', 'gelb'],
  LA: ['rot', 'blau', 'weiß'],
  LV: ['rot', 'weiß'],
  LB: ['rot', 'weiß', 'grün'],
  LS: ['blau', 'weiß', 'grün'],
  LR: ['rot', 'weiß', 'blau'],
  LY: ['rot', 'schwarz', 'grün', 'weiß'],
  LI: ['blau', 'rot'],
  LT: ['gelb', 'grün', 'rot'],
  LU: ['rot', 'weiß', 'blau'],
  MG: ['weiß', 'rot', 'grün'],
  MW: ['schwarz', 'rot', 'grün'],
  MY: ['rot', 'weiß', 'blau', 'gelb'],
  MV: ['grün', 'rot', 'weiß'],
  ML: ['grün', 'gelb', 'rot'],
  MT: ['weiß', 'rot'],
  MR: ['grün', 'gelb', 'rot'],
  MU: ['rot', 'blau', 'gelb', 'grün'],
  MX: ['grün', 'weiß', 'rot'],
  MD: ['blau', 'gelb', 'rot'],
  MN: ['rot', 'blau', 'gelb'],
  ME: ['rot', 'gelb'],
  MA: ['rot', 'grün'],
  MZ: ['grün', 'schwarz', 'gelb', 'weiß', 'rot'],
  MM: ['gelb', 'grün', 'rot', 'weiß'],
  NA: ['blau', 'rot', 'grün', 'weiß', 'gelb'],
  NP: ['rot', 'blau', 'weiß'],
  NL: ['rot', 'weiß', 'blau'],
  NZ: ['blau', 'rot', 'weiß'],
  NI: ['blau', 'weiß'],
  NE: ['orange', 'weiß', 'grün'],
  NG: ['grün', 'weiß'],
  KP: ['rot', 'weiß', 'blau'],
  MK: ['rot', 'gelb'],
  NO: ['rot', 'weiß', 'blau'],
  OM: ['weiß', 'rot', 'grün'],
  PK: ['grün', 'weiß'],
  PA: ['weiß', 'rot', 'blau'],
  PG: ['rot', 'schwarz', 'gelb', 'weiß'],
  PY: ['rot', 'weiß', 'blau'],
  PE: ['rot', 'weiß'],
  PH: ['blau', 'rot', 'weiß', 'gelb'],
  PL: ['weiß', 'rot'],
  PT: ['grün', 'rot', 'gelb'],
  QA: ['weiß', 'rot'],
  RO: ['blau', 'gelb', 'rot'],
  RU: ['weiß', 'blau', 'rot'],
  RW: ['blau', 'gelb', 'grün'],
  SA: ['grün', 'weiß'],
  SN: ['grün', 'gelb', 'rot'],
  RS: ['rot', 'blau', 'weiß'],
  SL: ['grün', 'weiß', 'blau'],
  SG: ['rot', 'weiß'],
  SK: ['weiß', 'blau', 'rot'],
  SI: ['weiß', 'blau', 'rot'],
  SB: ['blau', 'grün', 'gelb', 'weiß'],
  SO: ['blau', 'weiß'],
  ZA: ['rot', 'blau', 'grün', 'gelb', 'schwarz', 'weiß'],
  KR: ['weiß', 'rot', 'blau', 'schwarz'],
  SS: ['schwarz', 'rot', 'grün', 'blau', 'gelb', 'weiß'],
  ES: ['rot', 'gelb'],
  LK: ['gelb', 'rot', 'grün', 'orange'],
  SD: ['rot', 'weiß', 'schwarz', 'grün'],
  SR: ['grün', 'weiß', 'rot', 'gelb'],
  SE: ['blau', 'gelb'],
  CH: ['rot', 'weiß'],
  SY: ['rot', 'weiß', 'schwarz', 'grün'],
  TW: ['blau', 'rot', 'weiß'],
  TJ: ['rot', 'weiß', 'grün', 'gelb'],
  TZ: ['grün', 'gelb', 'blau', 'schwarz'],
  TH: ['rot', 'weiß', 'blau'],
  TL: ['rot', 'gelb', 'schwarz', 'weiß'],
  TG: ['grün', 'gelb', 'rot', 'weiß'],
  TT: ['rot', 'weiß', 'schwarz'],
  TN: ['rot', 'weiß'],
  TR: ['rot', 'weiß'],
  TM: ['grün', 'weiß', 'rot', 'gelb'],
  UG: ['schwarz', 'gelb', 'rot'],
  UA: ['blau', 'gelb'],
  AE: ['grün', 'weiß', 'schwarz', 'rot'],
  GB: ['blau', 'rot', 'weiß'],
  US: ['rot', 'weiß', 'blau'],
  UY: ['weiß', 'blau', 'gelb'],
  UZ: ['blau', 'weiß', 'grün', 'rot'],
  VU: ['rot', 'grün', 'schwarz', 'gelb'],
  VE: ['gelb', 'blau', 'rot'],
  VN: ['rot', 'gelb'],
  YE: ['rot', 'weiß', 'schwarz'],
  ZM: ['grün', 'orange', 'rot', 'schwarz'],
  ZW: ['grün', 'gelb', 'rot', 'schwarz', 'weiß'],
}

export function flagColorsOf(countryId: string): FlagColor[] {
  const a2 = alpha2Of(countryId)
  if (!a2) return []
  return FLAG_COLORS_A2[a2] ?? []
}

export function flagHasColor(countryId: string, color: FlagColor): boolean {
  return flagColorsOf(countryId).includes(color)
}

export function flagColorLabel(color: FlagColor): string {
  return FLAG_COLOR_OPTIONS.find((c) => c.id === color)?.label ?? color
}

export function flagColorHex(color: FlagColor): string {
  return FLAG_COLOR_OPTIONS.find((c) => c.id === color)?.hex ?? '#888'
}
