import { alpha2Of } from './isoAlpha2'

/** Flaggenfarben (deutsch), grob nach sichtbaren Hauptfarben */
export type FlagColor =
  | 'red'
  | 'blue'
  | 'green'
  | 'yellow'
  | 'black'
  | 'white'
  | 'orange'

export const FLAG_COLOR_OPTIONS: { id: FlagColor; hex: string }[] = [
  { id: 'red', hex: '#c45c4a' },
  { id: 'blue', hex: '#3a7ab8' },
  { id: 'green', hex: '#3aa87a' },
  { id: 'yellow', hex: '#e0b84a' },
  { id: 'black', hex: '#1a1a1a' },
  { id: 'white', hex: '#eef6f4' },
  { id: 'orange', hex: '#f0a35e' },
]

/** ISO alpha-2 → Farben in der Nationalflagge */
const FLAG_COLORS_A2: Record<string, FlagColor[]> = {
  AG: ['red', 'blue', 'yellow', 'black', 'white'],
  BS: ['blue', 'yellow', 'black'],
  BB: ['blue', 'yellow', 'black'],
  KM: ['yellow', 'white', 'red', 'blue', 'green'],
  DM: ['green', 'yellow', 'black', 'white', 'red'],
  PS: ['black', 'white', 'green', 'red'],
  PR: ['red', 'white', 'blue'],
  EH: ['black', 'white', 'green', 'red'],
  GL: ['red', 'white'],
  NC: ['blue', 'red', 'green'],
  AQ: ['white', 'blue'],
  FK: ['blue', 'white', 'red'],
  TF: ['blue', 'white', 'red'],
  AF: ['black', 'red', 'green'],
  AL: ['red', 'black'],
  DZ: ['green', 'white', 'red'],
  AD: ['blue', 'yellow', 'red'],
  AO: ['red', 'black', 'yellow'],
  AR: ['blue', 'white', 'yellow'],
  AM: ['red', 'blue', 'orange'],
  AU: ['blue', 'red', 'white'],
  AT: ['red', 'white'],
  AZ: ['blue', 'red', 'green'],
  BH: ['red', 'white'],
  BD: ['green', 'red'],
  BY: ['red', 'green', 'white'],
  BE: ['black', 'yellow', 'red'],
  BZ: ['blue', 'red', 'white'],
  BJ: ['green', 'yellow', 'red'],
  BT: ['yellow', 'orange', 'white'],
  BO: ['red', 'yellow', 'green'],
  BA: ['blue', 'yellow', 'white'],
  BW: ['blue', 'black', 'white'],
  BR: ['green', 'yellow', 'blue'],
  BN: ['yellow', 'white', 'black', 'red'],
  BG: ['white', 'green', 'red'],
  BF: ['red', 'green', 'yellow'],
  BI: ['red', 'white', 'green'],
  CV: ['blue', 'white', 'red', 'yellow'],
  KH: ['blue', 'red', 'white'],
  CM: ['green', 'red', 'yellow'],
  CA: ['red', 'white'],
  CF: ['blue', 'white', 'green', 'yellow', 'red'],
  TD: ['blue', 'yellow', 'red'],
  CL: ['blue', 'white', 'red'],
  CN: ['red', 'yellow'],
  CO: ['yellow', 'blue', 'red'],
  CG: ['green', 'yellow', 'red'],
  CD: ['blue', 'yellow', 'red'],
  CR: ['blue', 'white', 'red'],
  CI: ['orange', 'white', 'green'],
  HR: ['red', 'white', 'blue'],
  CU: ['blue', 'white', 'red'],
  CY: ['white', 'orange'],
  CZ: ['white', 'red', 'blue'],
  DK: ['red', 'white'],
  DJ: ['blue', 'green', 'white', 'red'],
  DO: ['blue', 'red', 'white'],
  EC: ['yellow', 'blue', 'red'],
  EG: ['red', 'white', 'black'],
  SV: ['blue', 'white'],
  GQ: ['green', 'white', 'red', 'blue'],
  ER: ['green', 'blue', 'red', 'yellow'],
  EE: ['blue', 'black', 'white'],
  SZ: ['blue', 'yellow', 'red', 'black'],
  ET: ['green', 'yellow', 'red'],
  FJ: ['blue', 'white', 'red'],
  FI: ['white', 'blue'],
  FR: ['blue', 'white', 'red'],
  GA: ['green', 'yellow', 'blue'],
  GM: ['red', 'blue', 'green', 'white'],
  GE: ['white', 'red'],
  DE: ['black', 'red', 'yellow'],
  GH: ['red', 'yellow', 'green', 'black'],
  GR: ['blue', 'white'],
  GT: ['blue', 'white'],
  GN: ['red', 'yellow', 'green'],
  GW: ['red', 'yellow', 'green', 'black'],
  GY: ['green', 'yellow', 'red', 'black', 'white'],
  HT: ['blue', 'red'],
  HN: ['blue', 'white'],
  HU: ['red', 'white', 'green'],
  IS: ['blue', 'white', 'red'],
  IN: ['orange', 'white', 'green'],
  ID: ['red', 'white'],
  IR: ['green', 'white', 'red'],
  IQ: ['red', 'white', 'black', 'green'],
  IE: ['green', 'white', 'orange'],
  IL: ['white', 'blue'],
  IT: ['green', 'white', 'red'],
  JM: ['green', 'yellow', 'black'],
  JP: ['white', 'red'],
  JO: ['black', 'white', 'green', 'red'],
  KZ: ['blue', 'yellow'],
  KE: ['black', 'red', 'green', 'white'],
  KW: ['green', 'white', 'red', 'black'],
  KG: ['red', 'yellow'],
  LA: ['red', 'blue', 'white'],
  LV: ['red', 'white'],
  LB: ['red', 'white', 'green'],
  LS: ['blue', 'white', 'green'],
  LR: ['red', 'white', 'blue'],
  LY: ['red', 'black', 'green', 'white'],
  LI: ['blue', 'red'],
  LT: ['yellow', 'green', 'red'],
  LU: ['red', 'white', 'blue'],
  MG: ['white', 'red', 'green'],
  MW: ['black', 'red', 'green'],
  MY: ['red', 'white', 'blue', 'yellow'],
  MV: ['green', 'red', 'white'],
  ML: ['green', 'yellow', 'red'],
  MT: ['white', 'red'],
  MR: ['green', 'yellow', 'red'],
  MU: ['red', 'blue', 'yellow', 'green'],
  MX: ['green', 'white', 'red'],
  MD: ['blue', 'yellow', 'red'],
  MN: ['red', 'blue', 'yellow'],
  ME: ['red', 'yellow'],
  MA: ['red', 'green'],
  MZ: ['green', 'black', 'yellow', 'white', 'red'],
  MM: ['yellow', 'green', 'red', 'white'],
  NA: ['blue', 'red', 'green', 'white', 'yellow'],
  NP: ['red', 'blue', 'white'],
  NL: ['red', 'white', 'blue'],
  NZ: ['blue', 'red', 'white'],
  NI: ['blue', 'white'],
  NE: ['orange', 'white', 'green'],
  NG: ['green', 'white'],
  KP: ['red', 'white', 'blue'],
  MK: ['red', 'yellow'],
  NO: ['red', 'white', 'blue'],
  OM: ['white', 'red', 'green'],
  PK: ['green', 'white'],
  PA: ['white', 'red', 'blue'],
  PG: ['red', 'black', 'yellow', 'white'],
  PY: ['red', 'white', 'blue'],
  PE: ['red', 'white'],
  PH: ['blue', 'red', 'white', 'yellow'],
  PL: ['white', 'red'],
  PT: ['green', 'red', 'yellow'],
  QA: ['white', 'red'],
  RO: ['blue', 'yellow', 'red'],
  RU: ['white', 'blue', 'red'],
  RW: ['blue', 'yellow', 'green'],
  SA: ['green', 'white'],
  SN: ['green', 'yellow', 'red'],
  RS: ['red', 'blue', 'white'],
  SL: ['green', 'white', 'blue'],
  SG: ['red', 'white'],
  SK: ['white', 'blue', 'red'],
  SI: ['white', 'blue', 'red'],
  SB: ['blue', 'green', 'yellow', 'white'],
  SO: ['blue', 'white'],
  ZA: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
  KR: ['white', 'red', 'blue', 'black'],
  SS: ['black', 'red', 'green', 'blue', 'yellow', 'white'],
  ES: ['red', 'yellow'],
  LK: ['yellow', 'red', 'green', 'orange'],
  SD: ['red', 'white', 'black', 'green'],
  SR: ['green', 'white', 'red', 'yellow'],
  SE: ['blue', 'yellow'],
  CH: ['red', 'white'],
  SY: ['red', 'white', 'black', 'green'],
  TW: ['blue', 'red', 'white'],
  TJ: ['red', 'white', 'green', 'yellow'],
  TZ: ['green', 'yellow', 'blue', 'black'],
  TH: ['red', 'white', 'blue'],
  TL: ['red', 'yellow', 'black', 'white'],
  TG: ['green', 'yellow', 'red', 'white'],
  TT: ['red', 'white', 'black'],
  TN: ['red', 'white'],
  TR: ['red', 'white'],
  TM: ['green', 'white', 'red', 'yellow'],
  UG: ['black', 'yellow', 'red'],
  UA: ['blue', 'yellow'],
  AE: ['green', 'white', 'black', 'red'],
  GB: ['blue', 'red', 'white'],
  US: ['red', 'white', 'blue'],
  UY: ['white', 'blue', 'yellow'],
  UZ: ['blue', 'white', 'green', 'red'],
  VU: ['red', 'green', 'black', 'yellow'],
  VE: ['yellow', 'blue', 'red'],
  VN: ['red', 'yellow'],
  YE: ['red', 'white', 'black'],
  ZM: ['green', 'orange', 'red', 'black'],
  ZW: ['green', 'yellow', 'red', 'black', 'white'],
}

export function flagColorsOf(countryId: string): FlagColor[] {
  const a2 = alpha2Of(countryId)
  if (!a2) return []
  return FLAG_COLORS_A2[a2] ?? []
}

export function flagHasColor(countryId: string, color: FlagColor): boolean {
  return flagColorsOf(countryId).includes(color)
}

export function flagColorLabelKey(color: FlagColor): 'colorRed' | 'colorBlue' | 'colorGreen' | 'colorYellow' | 'colorBlack' | 'colorWhite' | 'colorOrange' {
  const keys = {
    red: 'colorRed',
    blue: 'colorBlue',
    green: 'colorGreen',
    yellow: 'colorYellow',
    black: 'colorBlack',
    white: 'colorWhite',
    orange: 'colorOrange',
  } as const
  return keys[color]
}

export function flagColorHex(color: FlagColor): string {
  return FLAG_COLOR_OPTIONS.find((c) => c.id === color)?.hex ?? '#888'
}
