/** ISO 3166-2 Region-ID → Hauptstadt (deutsch) */
export const REGION_CAPITALS_DE: Record<string, string> = {
  // Deutschland
  'DE-BW': 'Stuttgart',
  'DE-BY': 'München',
  'DE-BE': 'Berlin',
  'DE-BB': 'Potsdam',
  'DE-HB': 'Bremen',
  'DE-HH': 'Hamburg',
  'DE-HE': 'Wiesbaden',
  'DE-MV': 'Schwerin',
  'DE-NI': 'Hannover',
  'DE-NW': 'Düsseldorf',
  'DE-RP': 'Mainz',
  'DE-SL': 'Saarbrücken',
  'DE-SN': 'Dresden',
  'DE-ST': 'Magdeburg',
  'DE-SH': 'Kiel',
  'DE-TH': 'Erfurt',

  // Österreich
  'AT-1': 'Eisenstadt',
  'AT-2': 'Klagenfurt',
  'AT-3': 'Sankt Pölten',
  'AT-4': 'Linz',
  'AT-5': 'Salzburg',
  'AT-6': 'Graz',
  'AT-7': 'Innsbruck',
  'AT-8': 'Bregenz',
  'AT-9': 'Wien',

  // Schweiz
  'CH-ZH': 'Zürich',
  'CH-BE': 'Bern',
  'CH-LU': 'Luzern',
  'CH-UR': 'Altdorf',
  'CH-SZ': 'Schwyz',
  'CH-OW': 'Sarnen',
  'CH-NW': 'Stans',
  'CH-GL': 'Glarus',
  'CH-ZG': 'Zug',
  'CH-FR': 'Freiburg',
  'CH-SO': 'Solothurn',
  'CH-BS': 'Basel',
  'CH-BL': 'Liestal',
  'CH-SH': 'Schaffhausen',
  'CH-AR': 'Herisau',
  'CH-AI': 'Appenzell',
  'CH-SG': 'St. Gallen',
  'CH-GR': 'Chur',
  'CH-AG': 'Aarau',
  'CH-TG': 'Frauenfeld',
  'CH-TI': 'Bellinzona',
  'CH-VD': 'Lausanne',
  'CH-VS': 'Sitten',
  'CH-NE': 'Neuenburg',
  'CH-GE': 'Genf',
  'CH-JU': 'Delsberg',

  // USA
  'US-AL': 'Montgomery',
  'US-AK': 'Juneau',
  'US-AZ': 'Phoenix',
  'US-AR': 'Little Rock',
  'US-CA': 'Sacramento',
  'US-CO': 'Denver',
  'US-CT': 'Hartford',
  'US-DE': 'Dover',
  'US-DC': 'Washington, D.C.',
  'US-FL': 'Tallahassee',
  'US-GA': 'Atlanta',
  'US-HI': 'Honolulu',
  'US-ID': 'Boise',
  'US-IL': 'Springfield',
  'US-IN': 'Indianapolis',
  'US-IA': 'Des Moines',
  'US-KS': 'Topeka',
  'US-KY': 'Frankfort',
  'US-LA': 'Baton Rouge',
  'US-ME': 'Augusta',
  'US-MD': 'Annapolis',
  'US-MA': 'Boston',
  'US-MI': 'Lansing',
  'US-MN': 'Saint Paul',
  'US-MS': 'Jackson',
  'US-MO': 'Jefferson City',
  'US-MT': 'Helena',
  'US-NE': 'Lincoln',
  'US-NV': 'Carson City',
  'US-NH': 'Concord',
  'US-NJ': 'Trenton',
  'US-NM': 'Santa Fe',
  'US-NY': 'Albany',
  'US-NC': 'Raleigh',
  'US-ND': 'Bismarck',
  'US-OH': 'Columbus',
  'US-OK': 'Oklahoma City',
  'US-OR': 'Salem',
  'US-PA': 'Harrisburg',
  'US-RI': 'Providence',
  'US-SC': 'Columbia',
  'US-SD': 'Pierre',
  'US-TN': 'Nashville',
  'US-TX': 'Austin',
  'US-UT': 'Salt Lake City',
  'US-VT': 'Montpelier',
  'US-VA': 'Richmond',
  'US-WA': 'Olympia',
  'US-WV': 'Charleston',
  'US-WI': 'Madison',
  'US-WY': 'Cheyenne',

  // Kanada
  'CA-AB': 'Edmonton',
  'CA-BC': 'Victoria',
  'CA-MB': 'Winnipeg',
  'CA-NB': 'Fredericton',
  'CA-NL': 'St. John’s',
  'CA-NS': 'Halifax',
  'CA-ON': 'Toronto',
  'CA-PE': 'Charlottetown',
  'CA-QC': 'Québec',
  'CA-SK': 'Regina',
  'CA-NT': 'Yellowknife',
  'CA-NU': 'Iqaluit',
  'CA-YT': 'Whitehorse',

  // Australien
  'AU-NSW': 'Sydney',
  'AU-VIC': 'Melbourne',
  'AU-QLD': 'Brisbane',
  'AU-SA': 'Adelaide',
  'AU-WA': 'Perth',
  'AU-TAS': 'Hobart',
  'AU-NT': 'Darwin',
  'AU-ACT': 'Canberra',

  // Brasilien
  'BR-AC': 'Rio Branco',
  'BR-AL': 'Maceió',
  'BR-AP': 'Macapá',
  'BR-AM': 'Manaus',
  'BR-BA': 'Salvador',
  'BR-CE': 'Fortaleza',
  'BR-DF': 'Brasília',
  'BR-ES': 'Vitória',
  'BR-GO': 'Goiânia',
  'BR-MA': 'São Luís',
  'BR-MT': 'Cuiabá',
  'BR-MS': 'Campo Grande',
  'BR-MG': 'Belo Horizonte',
  'BR-PA': 'Belém',
  'BR-PB': 'João Pessoa',
  'BR-PR': 'Curitiba',
  'BR-PE': 'Recife',
  'BR-PI': 'Teresina',
  'BR-RJ': 'Rio de Janeiro',
  'BR-RN': 'Natal',
  'BR-RS': 'Porto Alegre',
  'BR-RO': 'Porto Velho',
  'BR-RR': 'Boa Vista',
  'BR-SC': 'Florianópolis',
  'BR-SP': 'São Paulo',
  'BR-SE': 'Aracaju',
  'BR-TO': 'Palmas',

  // Mexiko
  'MX-AGU': 'Aguascalientes',
  'MX-BCN': 'Mexicali',
  'MX-BCS': 'La Paz',
  'MX-CAM': 'Campeche',
  'MX-CHP': 'Tuxtla Gutiérrez',
  'MX-CHH': 'Chihuahua',
  'MX-COA': 'Saltillo',
  'MX-COL': 'Colima',
  'MX-DUR': 'Durango',
  'MX-GUA': 'Guanajuato',
  'MX-GRO': 'Chilpancingo',
  'MX-HID': 'Pachuca',
  'MX-JAL': 'Guadalajara',
  'MX-MEX': 'Toluca',
  'MX-MIC': 'Morelia',
  'MX-MOR': 'Cuernavaca',
  'MX-NAY': 'Tepic',
  'MX-NLE': 'Monterrey',
  'MX-OAX': 'Oaxaca',
  'MX-PUE': 'Puebla',
  'MX-QUE': 'Querétaro',
  'MX-ROO': 'Chetumal',
  'MX-SLP': 'San Luis Potosí',
  'MX-SIN': 'Culiacán',
  'MX-SON': 'Hermosillo',
  'MX-TAB': 'Villahermosa',
  'MX-TAM': 'Ciudad Victoria',
  'MX-TLA': 'Tlaxcala',
  'MX-VER': 'Xalapa',
  'MX-YUC': 'Mérida',
  'MX-ZAC': 'Zacatecas',

  // Polen
  'PL-DS': 'Breslau',
  'PL-KP': 'Bydgoszcz',
  'PL-LU': 'Lublin',
  'PL-LB': 'Gorzów Wielkopolski',
  'PL-LD': 'Łódź',
  'PL-MA': 'Krakau',
  'PL-MZ': 'Warschau',
  'PL-OP': 'Opole',
  'PL-PK': 'Rzeszów',
  'PL-PD': 'Białystok',
  'PL-PM': 'Danzig',
  'PL-SL': 'Katowice',
  'PL-SK': 'Kielce',
  'PL-WN': 'Olsztyn',
  'PL-WP': 'Posen',
  'PL-ZP': 'Stettin',

  // Südafrika
  'ZA-EC': 'Bhisho',
  'ZA-FS': 'Bloemfontein',
  'ZA-GT': 'Johannesburg',
  'ZA-NL': 'Pietermaritzburg',
  'ZA-LP': 'Polokwane',
  'ZA-MP': 'Mbombela',
  'ZA-NW': 'Mahikeng',
  'ZA-NC': 'Kimberley',
  'ZA-WC': 'Kapstadt',

  // Belgien
  'BE-VAN': 'Antwerpen',
  'BE-VBR': 'Löwen',
  'BE-VLI': 'Hasselt',
  'BE-VOV': 'Gent',
  'BE-VWV': 'Brügge',
  'BE-WBR': 'Wavre',
  'BE-WHT': 'Mons',
  'BE-WLG': 'Lüttich',
  'BE-WLX': 'Arlon',
  'BE-WNA': 'Namur',
  'BE-BRU': 'Brüssel',

  // Argentinien
  'AR-A': 'Salta',
  'AR-B': 'La Plata',
  'AR-C': 'Buenos Aires',
  'AR-D': 'San Luis',
  'AR-E': 'Paraná',
  'AR-F': 'La Rioja',
  'AR-G': 'Santiago del Estero',
  'AR-H': 'Resistencia',
  'AR-J': 'San Juan',
  'AR-K': 'San Fernando del Valle de Catamarca',
  'AR-L': 'Santa Rosa',
  'AR-M': 'Mendoza',
  'AR-N': 'Posadas',
  'AR-P': 'Formosa',
  'AR-Q': 'Neuquén',
  'AR-R': 'Viedma',
  'AR-S': 'Santa Fe',
  'AR-T': 'San Miguel de Tucumán',
  'AR-U': 'Rawson',
  'AR-V': 'Ushuaia',
  'AR-W': 'Corrientes',
  'AR-X': 'Córdoba',
  'AR-Y': 'San Salvador de Jujuy',
  'AR-Z': 'Río Gallegos',

  // Neuseeland
  'NZ-AUK': 'Auckland',
  'NZ-BOP': 'Whakatāne',
  'NZ-CAN': 'Christchurch',
  'NZ-GIS': 'Gisborne',
  'NZ-HKB': 'Napier',
  'NZ-MWT': 'Palmerston North',
  'NZ-MBH': 'Blenheim',
  'NZ-NSN': 'Nelson',
  'NZ-NTL': 'Whangārei',
  'NZ-OTA': 'Dunedin',
  'NZ-STL': 'Invercargill',
  'NZ-TAS': 'Richmond',
  'NZ-TKI': 'New Plymouth',
  'NZ-WGN': 'Wellington',
  'NZ-WKO': 'Hamilton',
  'NZ-WTC': 'Greymouth',
  'NZ-CIT': 'Waitangi',

  // Japan (Präfekturhauptstädte)
  'JP-01': 'Sapporo',
  'JP-02': 'Aomori',
  'JP-03': 'Morioka',
  'JP-04': 'Sendai',
  'JP-05': 'Akita',
  'JP-06': 'Yamagata',
  'JP-07': 'Fukushima',
  'JP-08': 'Mito',
  'JP-09': 'Utsunomiya',
  'JP-10': 'Maebashi',
  'JP-11': 'Saitama',
  'JP-12': 'Chiba',
  'JP-13': 'Tokio',
  'JP-14': 'Yokohama',
  'JP-15': 'Niigata',
  'JP-16': 'Toyama',
  'JP-17': 'Kanazawa',
  'JP-18': 'Fukui',
  'JP-19': 'Kōfu',
  'JP-20': 'Nagano',
  'JP-21': 'Gifu',
  'JP-22': 'Shizuoka',
  'JP-23': 'Nagoya',
  'JP-24': 'Tsu',
  'JP-25': 'Ōtsu',
  'JP-26': 'Kyōto',
  'JP-27': 'Osaka',
  'JP-28': 'Kōbe',
  'JP-29': 'Nara',
  'JP-30': 'Wakayama',
  'JP-31': 'Tottori',
  'JP-32': 'Matsue',
  'JP-33': 'Okayama',
  'JP-34': 'Hiroshima',
  'JP-35': 'Yamaguchi',
  'JP-36': 'Tokushima',
  'JP-37': 'Takamatsu',
  'JP-38': 'Matsuyama',
  'JP-39': 'Kōchi',
  'JP-40': 'Fukuoka',
  'JP-41': 'Saga',
  'JP-42': 'Nagasaki',
  'JP-43': 'Kumamoto',
  'JP-44': 'Ōita',
  'JP-45': 'Miyazaki',
  'JP-46': 'Kagoshima',
  'JP-47': 'Naha',

  // Indien
  'IN-AN': 'Port Blair',
  'IN-AP': 'Amaravati',
  'IN-AR': 'Itanagar',
  'IN-AS': 'Dispur',
  'IN-BR': 'Patna',
  'IN-CH': 'Chandigarh',
  'IN-CT': 'Raipur',
  'IN-DH': 'Daman',
  'IN-DL': 'Neu-Delhi',
  'IN-GA': 'Panaji',
  'IN-GJ': 'Gandhinagar',
  'IN-HR': 'Chandigarh',
  'IN-HP': 'Shimla',
  'IN-JH': 'Ranchi',
  'IN-JK': 'Srinagar',
  'IN-KA': 'Bengaluru',
  'IN-KL': 'Thiruvananthapuram',
  'IN-LA': 'Leh',
  'IN-LD': 'Kavaratti',
  'IN-MH': 'Mumbai',
  'IN-ML': 'Shillong',
  'IN-MN': 'Imphal',
  'IN-MP': 'Bhopal',
  'IN-MZ': 'Aizawl',
  'IN-NL': 'Kohima',
  'IN-OR': 'Bhubaneswar',
  'IN-PB': 'Chandigarh',
  'IN-PY': 'Puducherry',
  'IN-RJ': 'Jaipur',
  'IN-SK': 'Gangtok',
  'IN-TG': 'Hyderabad',
  'IN-TN': 'Chennai',
  'IN-TR': 'Agartala',
  'IN-UP': 'Lucknow',
  'IN-UT': 'Dehradun',
  'IN-WB': 'Kolkata',

  // China (Provinzhauptstädte)
  'CN-AH': 'Hefei',
  'CN-BJ': 'Peking',
  'CN-CQ': 'Chongqing',
  'CN-FJ': 'Fuzhou',
  'CN-GD': 'Guangzhou',
  'CN-GS': 'Lanzhou',
  'CN-GX': 'Nanning',
  'CN-GZ': 'Guiyang',
  'CN-HA': 'Zhengzhou',
  'CN-HB': 'Wuhan',
  'CN-HE': 'Shijiazhuang',
  'CN-HI': 'Haikou',
  'CN-HL': 'Harbin',
  'CN-HN': 'Changsha',
  'CN-JL': 'Changchun',
  'CN-JS': 'Nanjing',
  'CN-JX': 'Nanchang',
  'CN-LN': 'Shenyang',
  'CN-NM': 'Hohhot',
  'CN-NX': 'Yinchuan',
  'CN-QH': 'Xining',
  'CN-SC': 'Chengdu',
  'CN-SD': 'Jinan',
  'CN-SH': 'Shanghai',
  'CN-SN': 'Xi’an',
  'CN-SX': 'Taiyuan',
  'CN-TJ': 'Tianjin',
  'CN-XJ': 'Ürümqi',
  'CN-XZ': 'Lhasa',
  'CN-YN': 'Kunming',
  'CN-ZJ': 'Hangzhou',
}

export function regionCapitalOf(regionId: string): string | null {
  return REGION_CAPITALS_DE[regionId] ?? null
}

export function hasRegionCapital(regionId: string): boolean {
  return regionId in REGION_CAPITALS_DE
}
